// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeRogue.Infrastructure.Data;

#nullable disable

namespace PokeRogue.Infrastructure.Migrations
{
    [DbContext(typeof(PokeRogueDbContext))]
    [Migration("20260818100246_AddMorePokemonAndAttackLines")]
    partial class AddMorePokemonAndAttackLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PokeRogue.Domain.Entities.AttackLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage1Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage2Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage3Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage3Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AttackLines");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveOpponentPokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlayerTurn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerPokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.BattleOpponentPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartyPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonSpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("PokemonSpeciesId");

                    b.ToTable("BattleOpponentPokemon");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.BattlePlayerPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EligibleForLevelUp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunPokemonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("RunPokemonId");

                    b.ToTable("BattlePlayerPokemon");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.CatchOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonSpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonSpeciesId");

                    b.ToTable("CatchOptions");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.CatchZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonSpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonSpeciesId");

                    b.ToTable("CatchZones");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EffectType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetPokemonType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.ItemOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemOptions");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.MapConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToNodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId");

                    b.HasIndex("ToNodeId");

                    b.ToTable("MapConnections");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.MapNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFixedEvent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStartNode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MapNodes");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.PokemonSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseHp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpecialAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpecialDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttackLineId");

                    b.ToTable("PokemonSpecies");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentCity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.RunItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RunId");

                    b.ToTable("RunItems");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.RunNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MapNodeId");

                    b.HasIndex("RunId");

                    b.ToTable("RunNodes");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.RunPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeldItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartyPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonSpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("PokemonSpeciesId");

                    b.HasIndex("RunId");

                    b.ToTable("RunPokemon");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.TrainerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrainerTypes");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.BattleOpponentPokemon", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.Battle", "Battle")
                        .WithMany("OpponentPokemon")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeRogue.Domain.Entities.PokemonSpecies", "PokemonSpecies")
                        .WithMany()
                        .HasForeignKey("PokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("PokemonSpecies");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.BattlePlayerPokemon", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.Battle", "Battle")
                        .WithMany("PlayerParty")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeRogue.Domain.Entities.RunPokemon", "RunPokemon")
                        .WithMany()
                        .HasForeignKey("RunPokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("RunPokemon");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.CatchOption", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.PokemonSpecies", "PokemonSpecies")
                        .WithMany()
                        .HasForeignKey("PokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonSpecies");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.CatchZone", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.PokemonSpecies", "PokemonSpecies")
                        .WithMany()
                        .HasForeignKey("PokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonSpecies");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.ItemOption", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.MapConnection", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.MapNode", "FromNode")
                        .WithMany()
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeRogue.Domain.Entities.MapNode", "ToNode")
                        .WithMany()
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.PokemonSpecies", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.AttackLine", "AttackLine")
                        .WithMany()
                        .HasForeignKey("AttackLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttackLine");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.RunItem", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeRogue.Domain.Entities.Run", "Run")
                        .WithMany("Items")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.RunNode", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.MapNode", "MapNode")
                        .WithMany()
                        .HasForeignKey("MapNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeRogue.Domain.Entities.Run", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapNode");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.RunPokemon", b =>
                {
                    b.HasOne("PokeRogue.Domain.Entities.Item", "HeldItem")
                        .WithMany()
                        .HasForeignKey("HeldItemId");

                    b.HasOne("PokeRogue.Domain.Entities.PokemonSpecies", "PokemonSpecies")
                        .WithMany()
                        .HasForeignKey("PokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeRogue.Domain.Entities.Run", "Run")
                        .WithMany("Pokemon")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeldItem");

                    b.Navigation("PokemonSpecies");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.Battle", b =>
                {
                    b.Navigation("OpponentPokemon");

                    b.Navigation("PlayerParty");
                });

            modelBuilder.Entity("PokeRogue.Domain.Entities.Run", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Pokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
